server:
  port: 2026

spring:
  application:
    name: bank-transfer-app
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://pg-bankdb-dotmfb-shaibumiracle7-231b.d.aivencloud.com:28238/defaultdb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.transfer: INFO
    org.springframework: WARN

shedlock:
  defaults:
    lock-at-most-for: PT30M
    lock-at-least-for: PT5M

app:
  transfer:
    fee-cap: 100.0
    fee-rate: 0.005
    commission-rate: 0.20
  scheduler:
    commission-cron: "0 0 1 * * *"
    summary-cron: "0 30 1 * * *"